FROM node:8.12.0-stretch

MAINTAINER Erik Nygren <dev@erik.work>

# We need git
RUN apt-get update && apt-get install -y git-core

# Allow to run as user www-data
RUN chsh www-data -s /bin/sh

# Prepare git directory
RUN mkdir -p /srv/gitrepos/root \
    && chown www-data:www-data /srv/gitrepos

WORKDIR /srv/node

COPY package*.json ./
COPY backend ./backend

RUN npm install

EXPOSE 80
EXPOSE 9229

STOPSIGNAL SIGTERM

CMD npm start
